-- MySQL Script generated by MySQL Workbench
-- Thu Apr  1 18:50:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `world` DEFAULT CHARACTER SET utf8mb4;
USE `world`;

-- -----------------------------------------------------
-- Table `world`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`Countries` (
  `id` TINYINT UNSIGNED NOT NULL,
  `name` VARCHAR(36) NOT NULL,
  `iso3` CHAR(3) NOT NULL,
  `iso2` CHAR(2) NOT NULL,
  `dialing_code` VARCHAR(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `iso3_UNIQUE` (`iso3` ASC),
  UNIQUE INDEX `iso2_UNIQUE` (`iso2` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `world`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`States` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(59) NOT NULL,
  `iso2` VARCHAR(6) NOT NULL,
  `country_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_States-Countries_idx` (`country_id` ASC),
  CONSTRAINT `fk_States-Countries`
    FOREIGN KEY (`country_id`)
    REFERENCES `world`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `world`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`Cities` (
  `id` MEDIUMINT UNSIGNED NOT NULL,
  `name` VARCHAR(67) NOT NULL,
  `state_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Cities-States_idx` (`state_id` ASC),
  CONSTRAINT `fk_Cities-States`
    FOREIGN KEY (`state_id`)
    REFERENCES `world`.`States` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
